services:
  - type: web
    name: schoolsync-client-backend
    runtime: node
    rootDir: .
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
